name: Frontend Build and Test

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Specify the Node.js version you are using

      # Step 3: Navigate to the frontend/Demarket directory
      - name: Change to frontend/Demarket directory
        run: cd frontend/Demarket

      # Step 4: Install dependencies
      - name: Install dependencies
        run: npm install
        working-directory: frontend/Demarket

      # Step 5: Run tests
      - name: Run tests
        run: npm test
        working-directory: frontend/Demarket

      # Step 6: Build the project
      - name: Build the project
        run: npm run build
        working-directory: frontend/Demarket

      # Step 7: Upload build artifacts (optional)
      - name: Upload build artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: frontend/Demarket/dist/ # Adjust this path based on the build output
